name: Export Tailscale Docker Image

on:
  workflow_dispatch:

jobs:
  export:
    runs-on: ubuntu-latest

    steps:
      - name: Pull image
        run: docker pull tailscale/tailscale:latest

      - name: Save image
        run: docker save tailscale/tailscale:latest -o tailscale.tar

      - name: Compress image
        run: gzip -9 tailscale.tar

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: tailscale-image
          path: tailscale.tar.gz
